# Generated by Django 5.0.4 on 2024-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='books_book_code_89b4cf_idx')],
            },
        ),
    ]
