# Generated by Django 5.0.4 on 2024-05-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='idx_author_code')],
            },
        ),
    ]
