# Generated by Django 5.0.4 on 2024-05-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='aba_code_idx')],
            },
        ),
    ]
