# Generated by Django 5.0.4 on 2024-04-30 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('nomenclature', models.CharField(blank=True, max_length=21)),
                ('code', models.CharField(blank=True, max_length=150, unique=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=210)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=210, unique=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_name_693421_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=210, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='current_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=210),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', to_field='code'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['code'], name='products_ca_code_b044cd_idx'),
        ),
        migrations.AddIndex(
            model_name='productmeasurement',
            index=models.Index(fields=['code'], name='products_pr_code_215f9b_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurements',
            field=models.ManyToManyField(blank=True, to='products.productmeasurement'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['code'], name='products_su_code_ede87a_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory', to_field='code'),
        ),
    ]
