# Generated by Django 5.0.4 on 2024-04-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
