# Generated by Django 5.0.4 on 2024-04-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='average_rating',
        ),
    ]
