# Generated by Django 5.0.4 on 2024-05-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_creado_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='creado_en',
        ),
    ]
